### PR TITLE
Add Logo

### PR DESCRIPTION
**Pull request by ybreza**
All Done

### CODE REVIEW

**Comment by funilrys** [comment]
Great but I said a `.assets/logo` directory not a `logo/` :joy: 

Anyway simply commit the changes to your branch no need to create a new PR.

Is it possible to have all other colors too?

Is it possible to have them all in a larger format? Because if for example, I want to produce a T-Shirt with that logo we will have a big pixelization issue ...

**Comment by ybreza** [comment]
i'll make it for you, hold on sir

btw, im so sorry im not familiar with github :laughing:

**Comment by ybreza** [comment]
All done sir, i have create All color 
And make ```.assets/logo``` too 

[GOOGLE DRIVE](https://drive.google.com/open?id=1HUZqQ8zWJ4xg0BmMyb2uSRpEkJpy1I2W)

**Comment by ybreza** [comment]
t-shirt mockup_front

Hi Sir, all done
I give you sample of T-Shirt Mockup for your aplication xD

Please check all of my commits, cant see them merge into dev

**Comment by funilrys** [comment]
@ybreza I was excepting something much more bigger!

**Comment by ybreza** [comment]
I put the logo more bigger on your ```readme.md``` sir

**Comment by funilrys** [comment]
Perfect! 


_____
Merging.

**Pull request merged**
