### PR TITLE
HELP WANTED | Let's switch to Markdown & mkdocs - from restructuredText & Sphinx

### PR DESCRIPTION
**Pull request by funilrys**
As mentioned in #340, it's time to move away from restructured text. 

This PR is a work in progress. - feel free to contribute!

### CODE REVIEW

**Comment by spirillen** [comment]
You should make sure`material.extensions' gets installed... (https://github.com/funilrys/PyFunceble/issues/340#issuecomment-1863938452)

**Comment by funilrys** [comment]
After each push into the `switch-to-mkdocs` branch, a new documentation will be published to https://hub.docker.com/r/pyfunceble/docs
and later automatically fetched and readable from https://docs.pyfunceble.com.

cc: @mitchellkrogza @spirillen

**Comment by spirillen** [comment]
> After each push into the `switch-to-mkdocs` branch, a new documentation will be published to https://hub.docker.com/r/pyfunceble/docs and later automatically fetched and readable from https://docs.pyfunceble.com.
> 
> cc: @mitchellkrogza @spirillen

I have made a fork and moved to https://github.com/foreign-affairs/PyFunceble-docs this repo will de docs only, and the default branch are changed to `switch-to-mkdocs` so for ease, would it be possible we made changes there, and then pushed here?

**Comment by spirillen** [comment]
What is destination folder and what is the old docs?

I assume https://github.com/funilrys/PyFunceble/tree/switch-to-mkdocs/docs is the new target while https://github.com/funilrys/PyFunceble/tree/switch-to-mkdocs/sphinx-docs should be considered as the source. right?

**Comment by funilrys** [comment]
merged. closing.

**Comment by funilrys** [comment]
@all-contributors 

please add @avatartw for bug.
please add @AvinashReddy3108 for bug.
please add @bigdargon for bug, ideas, question, review, data and test.
please add @dnmTX for bugs, ideas, question, review, data and test.
please add @gwarser for bug, data and test.
please add @veracioux for documentation, a11y, example, tool, test, video and tutorial.
please add @hawkeye116477 for bug.
please add @T145 for bug and ideas .
please add @DandelionSprout for a11y, bug, data, example, financial, ideas, promotion, question, review, tool, test and userTesting.

**Comment by funilrys** [comment]
@all-contributors please add @avatartw for bug.

**Comment by funilrys** [comment]
@all-contributors please add @avatartw for bug.

**Comment by funilrys** [comment]
https://github.com/all-contributors please add @avatartw for bug.

**Comment by funilrys** [comment]
@all-contributors please add @avatartw for bug.

**Pull request closed without merging**
