### PR TITLE
Fixes #285

### LINKED ISSUE #285: BUG: No package metadata was found for PyFunceble-dev
```py
[user@work ~]$ pyfunceble -w 32 -a --logging-level debug -f File.txt 
Traceback (most recent call last):
  File "/usr/bin/pyfunceble", line 33, in <module>
    sys.exit(load_entry_point('PyFunceble-dev==4.0.2b7', 'console_scripts', 'pyfunceble')())
  File "/usr/bin/pyfunceble", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for PyFunceble-dev
```
Reinstall via yay -S 

```py
[user@work ~]$ pyfunceble -w 32 -a --logging-level debug -f File.txt
Traceback (most recent call last):
  File "/usr/bin/pyfunceble", line 33, in <module>
    sys.exit(load_entry_point('PyFunceble-dev==4.0.2b7', 'console_scripts', 'pyfunceble')())
  File "/usr/bin/pyfunceble", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/PyFunceble/__init__.py", line 55, in <module>
    import PyFunceble.storage
  File "/usr/lib/python3.10/site-packages/PyFunceble/storage.py", line 58, in <module>
    from box import Box
ModuleNotFoundError: No module named 'box'
[user@work ~]$ 
```
Logfiles: https://drive.google.com/file/d/1gRgWN_wi1N_gf0FzFJsENw4aSgL4yLCV/view?usp=sharing

### PR DESCRIPTION
**Pull request by spirillen**
Closes https://github.com/funilrys/PyFunceble/issues/285

This commit should help any future issues related to python-box.

### CODE REVIEW

**Comment by ZeroDot1** [comment]
Thank you, that's exactly what I wanted to do, but unfortunately I did not have time. Real life was real and stressful for me today.

**Comment by spirillen** [comment]
Thats why we are here, to help each other the best we can.

Hoping Ihren wonung situation have improved since out last greeting.

**Comment by funilrys** [comment]
That was certainly an issue with the Arch Repo which I didn't update the last few weeks. 
I assume that my package update should fix this. 

I'm keeping this open until I can reproduce.

**Comment by funilrys** [comment]
Okay I found it!

Arch released a new minor Python Version. Meaning that all package had to be rebuilt. 

Therefore, this patch is unnecessary!

Thank you everyone and merry Christmas.
Best wishes 🎅

**Comment by ZeroDot1** [comment]
Hi @spirillen, I wish you and all who read this a happy new year, stay healthy.

The problem with my home, unfortunately, I have not yet been able to solve.

If you have Telegram, check out the following post: https://t.me/CoinBlockerLists/81 

Thank you.

**Comment by spirillen** [comment]
Hey @ZeroDot1 

I'm sad to hear that a country like Germany can't offer a single wonung, not that it is entirely better here up north, but if you are able to move to another part of the country, it is almost solvable. It is a extremely long time to go without a place to feel at home. It is a shame you can't work from DK,

And no I do not have any of chose spyware thingy like fuckbook telegram or a like, can't you just post a screen dump or copy / paste the lines.

**Comment by ZeroDot1** [comment]
Hi @spirillen thanks for your reply, here is the original text of the post: 

This year was a disaster for me, I lost my home through no fault of my own and my family stole from me. Now I have to take my own family to court, 
it's over 100000€ and my health is not OK either, I'm fighting with very high eye pressure.
But I don't give up the CoinBlockerLists even though I lost some of my equipment by losing my home.
I pay almost 115€ every month just for the internet so I can keep working on the project. Money is very limited because of this, unfortunately.
I hope the users who use all my lists appreciate the sacrifices I make to keep the project alive.
I thank everyone who supported me in 2021.

It will soon be my birthday, so I would greatly appreciate donations via my amazon wish list.

Link to my wish list: https://www.amazon.de/hz/wishlist/ls/2DDEDPJU2996I/?currency=EUR&language=en_GB 

Please share this if you would like to support me

I wish everyone a happy new year and stay healthy.

**Comment by ZeroDot1** [comment]
@spirillen I have already moved to another city, but getting an apartment is very difficult. This is due to the fact that the prices for living space in Germany are very high, and there are not enough livable apartments.
The German authorities have completely failed.

**Comment by spirillen** [comment]
> @spirillen I have already moved to another city, but getting an apartment is very difficult. This is due to the fact that the prices for living space in Germany are very high, and there are not enough livable apartments. The German authorities have completely failed.

You think the living cost are high in DE :smirk: I pay 72% of my income in rent alone, then there is all the other expenses like power, water etc. Some month I have less than €75 to food after expenses including those keeping mypdns alive.

And yes Angela Merkel and every other right wings parties have failed the past 100 years. And thinking of Angela Merkel politics as she comes from the old east Germany, something just seems so wrong.

**Pull request closed without merging**
