### PR TITLE
Draft: Updating text for -uf and other

### PR DESCRIPTION
**Pull request by spirillen**
Have tried to make the text for usage a bit more explainable for `--link` `-uf` 

A special note for [L585](https://github.com/funilrys/PyFunceble/pull/62/files#diff-ab65095dfe3815383d57be3a03cea929R585), that was, what I just could come up with!!!

This will be fixing #59

### CODE REVIEW

**Comment by spirillen** [comment]
Just a thought that comes up, while writing this....

What is the actually diff between `-f` and `--link`? if it is as I have understood it from [here](https://github.com/funilrys/PyFunceble/issues/59#issuecomment-554790423) that they are equal, why then have two commands for one job?

**Comment by funilrys** [comment]
Can you also apply your changes directly to the CLI (tool) itself ? It's into `PyFunceble/cli/__init__.py` 

P.S: Don't forget to bump the version (PyFunceble/abstracts/package.py) when you are done :smile:

**Comment by funilrys** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- PyFunceble/__init__.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/PyFunceble/PyFunceble/pullRequest?prid=4521447&bid=15228351)

**Comment by spirillen** [comment]
> Codacy Here is an overview of what got changed by this pull request:
> 
> ```diff
> Clones added
> ============
> - PyFunceble/__init__.py  1
>          
> ```
> 
> See the complete overview on [Codacy](https://app.codacy.com/app/PyFunceble/PyFunceble/pullRequest?prid=4521447&bid=15228351)

hmm can't see it :unamused:  keeps getting redirected to dashboard..

**Comment by funilrys** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- PyFunceble/__init__.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/PyFunceble/PyFunceble/pullRequest?prid=4521447&bid=15228351)

**Comment by funilrys** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- PyFunceble/__init__.py  52
         

Clones added
============
- PyFunceble/__init__.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/PyFunceble/PyFunceble/pullRequest?prid=4521447&bid=15228351)

**Comment by funilrys** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- PyFunceble/__init__.py  52
         

Clones added
============
- PyFunceble/__init__.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/PyFunceble/PyFunceble/pullRequest?prid=4521447&bid=15228351)

**Comment by funilrys** [comment]
You broke it because you started from the `master` instead of the `dev` branch! :smile_cat: 

If I merge this, it will be a catastrophe for every instance of PyFunceble in the world ... So  I manually merged it and let's continue there==>  #65

**Comment by spirillen** [comment]
> You broke it because you started from the `master` instead of the `dev` branch! smile_cat
> 

Hmmm I did ensure it said /dev, but something surely happen so we move along to #65

**Pull request closed without merging**
